theme = "catpuccin_mocha"

[editor]
line-number = "relative"
mouse = false
true-color = true
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "underline"
normal = "underline"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-j = "scroll_down"
C-k = "scroll_up"
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
